# Generated by Django 3.2.9 on 2021-11-20 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_paycheck', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_paycheck', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequency', models.IntegerField(choices=[(52, 'Weekly'), (26, 'Bi-weekly'), (24, 'Semi-monthly'), (12, 'Monthly'), (4, 'Quarterly'), (2, 'Semi-annually'), (1, 'Annually')], default=52)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequency', models.IntegerField(choices=[(52, 'Weekly'), (26, 'Bi-weekly'), (24, 'Semi-monthly'), (12, 'Monthly'), (4, 'Quarterly'), (2, 'Semi-annually'), (1, 'Annually')], default=52)),
                ('monthly_frequency', models.IntegerField(default=0)),
                ('per_paycheck_cost', models.IntegerField(default=0)),
                ('annual_cost', models.IntegerField(default=0)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='budget.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
