# Generated by Django 3.2.9 on 2021-12-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_auto_20211124_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='annual_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='monthly_frequency',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='per_paycheck_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='income',
            name='gross_paycheck',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='income',
            name='gross_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='income',
            name='net_paycheck',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='savings',
            name='annual_saving',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='savings',
            name='per_paycheck_saving',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
