# Generated by Django 3.2.9 on 2021-12-06 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0006_auto_20211201_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBudgetInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_income_frequency', models.IntegerField(choices=[(52, 'Weekly'), (26, 'Bi-weekly'), (24, 'Semi-monthly'), (12, 'Monthly'), (4, 'Quarterly'), (2, 'Semi-annually'), (1, 'Annually')], default=52)),
                ('total_gross_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_gross_paycheck', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_net_paycheck', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_paycheck_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_annual_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_paycheck_savings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_annual_savings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
