# Generated by Django 3.2.9 on 2021-12-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_userbudgetinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbudgetinfo',
            name='annual_pay_periods',
            field=models.IntegerField(default=52),
        ),
    ]
