# Generated by Django 3.2.9 on 2021-12-07 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_userbudgetinfo_annual_pay_periods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbudgetinfo',
            name='annual_pay_periods',
        ),
    ]
