# Generated by Django 3.2.9 on 2021-12-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_remove_userbudgetinfo_annual_pay_periods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='monthly_frequency',
        ),
        migrations.AlterField(
            model_name='expenses',
            name='frequency',
            field=models.IntegerField(choices=[(1, 'Monthly'), (2, 'Bi-monthly'), (3, 'Quarterly'), (6, 'Semi-annually'), (12, 'Annually'), (24, 'Bi-annually')], default=1),
        ),
    ]
