# Generated by Django 3.2.9 on 2021-12-06 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211129_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='total_annual_expenses',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='total_annual_savings',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='total_gross_paycheck',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='total_gross_salary',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='total_net_paycheck',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='total_paycheck_expenses',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='total_paycheck_savings',
        ),
    ]
